generic:
  mlock: false

  logging:
    stderr: false

  server:
    http_port: 8788
    https_port: 8789
    ca_cert_file: path/to/ca.crt
    ssl_cert_file: path/to/ssl.crt

  auth:
    token_file: path/to/tokenator_config

meta:
  meta_api_endpoint: grpc://localhost:2135
  meta_database: /root/ydb-meta
  meta_database_token_name: "meta-token"
